'use client';
import {Canvas, useFrame} from '@react-three/fiber';
import {Environment, Float, Instances, Instance, Stars} from '@react-three/drei';
import {EffectComposer, Bloom, DepthOfField} from '@react-three/postprocessing';
import {useEffect, useMemo, useRef} from 'react';
import * as THREE from 'three';
import gsap from 'gsap';import {ScrollTrigger} from 'gsap/ScrollTrigger';
import {useReducedMotion} from '@/hooks/useReducedMotion';
gsap.registerPlugin(ScrollTrigger);
function Sigil(){const group=useRef<THREE.Group>(null);const pulse=useRef<THREE.PointLight>(null);const mats=useMemo(()=>({metal:new THREE.MeshStandardMaterial({color:'#090a0d',metalness:.88,roughness:.27}),gold:new THREE.MeshStandardMaterial({color:'#d8b873',emissive:'#8d6821',emissiveIntensity:.8,metalness:.8,roughness:.2})}),[]);useFrame(({clock,pointer,camera})=>{const t=clock.elapsedTime;if(group.current){group.current.rotation.y=t*.08+pointer.x*.12;group.current.rotation.x=Math.sin(t*.3)*.05+pointer.y*.06} if(pulse.current) pulse.current.intensity=1.2+Math.sin(t*1.6)*.55; camera.position.x=THREE.MathUtils.lerp(camera.position.x,pointer.x*.35,.04);camera.position.y=THREE.MathUtils.lerp(camera.position.y,1+pointer.y*.18,.04);camera.lookAt(0,0,0)});return <group ref={group}>{Array.from({length:8}).map((_,i)=>{const a=i/8*Math.PI*2;return <group key={i} rotation={[0,0,a]} position={[Math.cos(a)*.05,Math.sin(a)*.05,0]}><mesh position={[1.05,0,0]} rotation={[0,0,.18]} castShadow receiveShadow material={mats.metal}><boxGeometry args={[1.05,.28,.16]}/></mesh><mesh position={[.49,0,.09]} material={mats.gold}><boxGeometry args={[.16,.035,.02]}/></mesh></group>})}<mesh><torusGeometry args={[.78,.018,12,128]}/><meshStandardMaterial color="#d8b873" emissive="#d8b873" emissiveIntensity={1.2}/></mesh><mesh><icosahedronGeometry args={[.42,2]}/><meshPhysicalMaterial color="#050609" metalness={.5} roughness={.18} transmission={.12} thickness={.4} emissive="#10264a" emissiveIntensity={.25}/></mesh><pointLight ref={pulse} color="#d8b873" distance={7} intensity={1.4}/></group>}
function Particles(){const points=useMemo(()=>Array.from({length:260},(_,i)=>({p:[(Math.random()-.5)*10,(Math.random()-.5)*7,(Math.random()-.5)*8] as [number,number,number],s:Math.random()*.035+.01})),[]);return <Instances limit={260}><sphereGeometry args={[1,8,8]}/><meshBasicMaterial color="#d8b873" transparent opacity={.42}/>{points.map((x,i)=><Instance key={i} position={x.p} scale={x.s}/>)}</Instances>}
function Scene(){const rig=useRef<THREE.Group>(null);useEffect(()=>{if(!rig.current)return;gsap.to(rig.current.rotation,{y:Math.PI*.55,scrollTrigger:{trigger:document.body,start:'top top',end:'bottom bottom',scrub:1}});gsap.to(rig.current.position,{z:-1.2,y:.45,scrollTrigger:{trigger:document.body,start:'20% top',end:'70% top',scrub:1}})},[]);return <group ref={rig}><fog attach="fog" args={['#030305',5,16]}/><color attach="background" args={['#030305']}/><ambientLight intensity={.18}/><directionalLight position={[-3,4,2]} color="#89a8df" intensity={1.2}/><spotLight position={[0,4,5]} angle={.45} penumbra={1} color="#d8b873" intensity={1.1}/><Float speed={1.2} rotationIntensity={.12} floatIntensity={.18}><Sigil/></Float><Particles/><Stars radius={18} depth={8} count={500} factor={2} saturation={0} fade speed={.35}/><mesh rotation={[-Math.PI/2,0,0]} position={[0,-1.05,0]} receiveShadow><circleGeometry args={[5,96]}/><meshStandardMaterial color="#050609" metalness={.6} roughness={.32}/></mesh><Environment preset="night"/></group>}
export default function AscendCanvas(){const reduced=useReducedMotion();return <div aria-hidden className="fixed inset-0 z-0"><Canvas shadows dpr={[1,1.65]} camera={{position:[0,1,5.2],fov:42}} gl={{antialias:true,powerPreference:'high-performance'}} performance={{min:.45}}>{!reduced&&<Scene/>}{reduced&&<><ambientLight intensity={.6}/><Sigil/></>} {!reduced&&<EffectComposer multisampling={0}><Bloom intensity={.45} luminanceThreshold={.18}/><DepthOfField focusDistance={.02} focalLength={.025} bokehScale={1.6}/></EffectComposer>}</Canvas></div>}
